language: node_js
node_js:
- 8
sudo: false
cache:
  directories:
  - node_modules
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/c8c40bc13ee38867f698
    on_success: change
    on_failure: always
    on_start: never
